server:
  port: 8762

eureka:
  instance:
    hostname: eureka-8762
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-8761:8761/eureka

spring:
  application:
    name: eureka-server
