eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/li1299657062/spring
          search-paths: classpath:/config
          username: 1299657062@qq.com
          password: li17671458461
      label: master

  application:
    name: config-server
server:
  port: 8888