eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.132:8761/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/li1299657062/spring
          search-paths: spring-cloud/config/src/main/resources/config
          username: 1299657062@qq.com
          password: li17671458461
      label: master

  application:
    name: config-server
server:
  port: 8888