eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-park:
      path: /ceicAdmin/park/**
      serviceId: park-server
      stripPrefix: false
