mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/ceic/park/mapper/*.xml
  type-aliases-package: com.ceic.park.model.*

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/ceic/mapper/*.xml
  type-aliases-package: com.ceic.model.*

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  offset-as-page-num: true
  row-bounds-with-count: true
  params: count=countSql

logging:
  level:
    org:
      mybatis: debug
    com:
      ceic:
        dao: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.132:8761/eureka
