spring:
  application:
    name: park-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: local
      label: master
      name: springCloud-ceic

server:
  port: 9100
  servlet:
    context-path: /ceicAdmin




